### ISSUE TITLE
Revise naming in configuration

### ISSUE THREAD

**Issue by filipsch** [krvajal/release-bot#67]
In #66, I used the following config:

```yaml
zenhub:
  board_id: "191731526"
  to_deploy_pipeline: "New Issues"
github:
  repo: 'github-admin'
  owner: 'sweepbright'
```

However, I am not sure whether `board_id` is the correct way to put it. `191731526` is the GitHub repo ID. This Python script shows it:

```python
from github import Github
import os
g = Github(os.environ.get("GITHUB_PAT"))
repos = { x.name: x for x in g.get_organization('SweepBright').get_repos() }
print(repos['github-admin'].id)
```

Output: `191731526`
